name: Run Groovy script

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Groovy tests
        run: gradle --stacktrace --debug --scan --init-script scripts/main.groovy --init-script scripts/main_test.groovy help
